/* Simulation code for OilSeparator_ThreePhase generated by the OpenModelica Compiler OpenModelica v1.24.4 (64-bit). */
#if !defined(OilSeparator_ThreePhase__MODEL_H)
#define OilSeparator_ThreePhase__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "OilSeparator_ThreePhase_functions.h"


extern void OilSeparator_ThreePhase_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void OilSeparator_ThreePhase_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void OilSeparator_ThreePhase_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int OilSeparator_ThreePhase_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_checkForAsserts(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int OilSeparator_ThreePhase_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* OilSeparator_ThreePhase_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* OilSeparator_ThreePhase_relationDescription(int i);
extern void OilSeparator_ThreePhase_function_initSample(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OilSeparator_ThreePhase_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OilSeparator_ThreePhase_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* OilSeparator_ThreePhase_linear_model_frame(void);
extern const char* OilSeparator_ThreePhase_linear_model_datarecovery_frame(void);
extern int OilSeparator_ThreePhase_mayer(DATA* data, modelica_real** res, short *);
extern int OilSeparator_ThreePhase_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int OilSeparator_ThreePhase_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int OilSeparator_ThreePhase_setInputData(DATA *data, const modelica_boolean file);
extern int OilSeparator_ThreePhase_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void OilSeparator_ThreePhase_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void OilSeparator_ThreePhase_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int OilSeparator_ThreePhase_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void OilSeparator_ThreePhase_read_simulation_info(SIMULATION_INFO* simulationData);
extern void OilSeparator_ThreePhase_read_input_fmu(MODEL_DATA* modelData);
extern void OilSeparator_ThreePhase_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int OilSeparator_ThreePhase_inputNames(DATA* data, char ** names);
extern int OilSeparator_ThreePhase_dataReconciliationInputNames(DATA* data, char ** names);
extern int OilSeparator_ThreePhase_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int OilSeparator_ThreePhase_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int OilSeparator_ThreePhase_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int OilSeparator_ThreePhase_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "OilSeparator_ThreePhase_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(OilSeparator_ThreePhase__MODEL_H) */


