/* Additional record code for OilSeparator_ThreePhase generated by the OpenModelica Compiler OpenModelica v1.24.4 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "OilSeparator_ThreePhase_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

