/* Simulation code for TankLevelControl generated by the OpenModelica Compiler OpenModelica v1.24.4 (64-bit). */
#if !defined(TankLevelControl__MODEL_H)
#define TankLevelControl__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "TankLevelControl_functions.h"


extern void TankLevelControl_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void TankLevelControl_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void TankLevelControl_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int TankLevelControl_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int TankLevelControl_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int TankLevelControl_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TankLevelControl_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TankLevelControl_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int TankLevelControl_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int TankLevelControl_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int TankLevelControl_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int TankLevelControl_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int TankLevelControl_checkForAsserts(DATA *data, threadData_t *threadData);
extern int TankLevelControl_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int TankLevelControl_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int TankLevelControl_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* TankLevelControl_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* TankLevelControl_relationDescription(int i);
extern void TankLevelControl_function_initSample(DATA *data, threadData_t *threadData);
extern int TankLevelControl_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TankLevelControl_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TankLevelControl_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* TankLevelControl_linear_model_frame(void);
extern const char* TankLevelControl_linear_model_datarecovery_frame(void);
extern int TankLevelControl_mayer(DATA* data, modelica_real** res, short *);
extern int TankLevelControl_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int TankLevelControl_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int TankLevelControl_setInputData(DATA *data, const modelica_boolean file);
extern int TankLevelControl_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void TankLevelControl_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void TankLevelControl_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int TankLevelControl_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void TankLevelControl_read_simulation_info(SIMULATION_INFO* simulationData);
extern void TankLevelControl_read_input_fmu(MODEL_DATA* modelData);
extern void TankLevelControl_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int TankLevelControl_inputNames(DATA* data, char ** names);
extern int TankLevelControl_dataReconciliationInputNames(DATA* data, char ** names);
extern int TankLevelControl_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int TankLevelControl_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int TankLevelControl_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int TankLevelControl_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "TankLevelControl_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(TankLevelControl__MODEL_H) */


